export const tokima_csv = `a,❗,onomatopoeia,particle,[emphasis],shows emphasis or emotion,,
aja,🧬,Arabic حياة ḥayāh ‘life’,modifier,alive,alive,,
ajuta,🚨,"Portuguese ajuda 'help, aid, assistance'",modifier,helpful,"helpful, assistive",,
aka,⛅,Bengali আকাশ aakaash,noun,sky,"sky, weather",,
aketi,🦎,Dutch hagedis ‘lizard’,noun,lizard,reptile or amphibian,,
akile,⏭️,Hindi अगले agle 'next',modifier,next,"next, coming, in the future",,
alasa,🏹,"Acadian French à la chasse ‘hunting’, from French chasser ‘to hunt’",verb,hunt,"to hunt, to forage, to gather, to find, to look for",,
ali,♾️,Dutch alle ‘all’,modifier,all,"all, countless, every, each",,
an,📍,Egyptian Arabic عند ʕand ‘at the house of’,preposition,at,"located at, present at",,
anpa,⬇️,Acadian French en bas ‘below’,noun,bottom,"bottom, lower part, bottom direction",,
ante,🔀,"Dutch ander ‘other, different’",modifier,different,"different, altered, changed, other",,
anu,☯️,Georgian ან an ‘or’,particle,or,or,,
apeja,😔,"Finnish häpeä ‘shame, disgrace, dishonor’",modifier,ashamed,"ashamed, disgraced, dishonored, guilty",,
atali,👑,"Gujarati આદર ādar 'respect, honor, admiration'",modifier,respectful,"respectful, honoring, admiring",,
ato,🚗,German auto 'car',verb,drive,to drive,,
awen,⚓,"Dutch houden ‘keep, care for, hold (in a particular state)’",modifier,staying,"staying, remaining, stationary, permanent, sedentary",,
awo,🔲,Yoruba awọ 'skin',irregular,skin,"(v) to touch, to contact (n) skin, outer edge (m) of the skin ",,
e,⏩,A priori word,preposition,[object],before the direct object,,
en,➕,Dutch en ‘and’,particle,[and],"between multiple subjects, between coordinate modifiers in a pi-phrase",,
enujo,🥱,"French ennuyeuse 'boring, annoying, tedious, dull'",modifier,bored,"bored, annoyed, dull",,
epi,🐋,English heavy,modifier,heavy,"heavy, thick, fat",,
esun,🛒,"Asante egŭaso, 'market, bazaar'",noun,shop,"market, shop, fair, bazaar, finance",,
ewin,💅,"Gaelic ewin 'clove, fingernail, prong, claw'",irregular,nail,"(v) to scratch (n) nail, hoof, claw, fingernail, prong, talon, horn (m) of the fingernail ",,
ike,👎,"Finnish ilkeä ‘bad, mean, wicked’",modifier,bad,bad,,
ilo,⚙️,"Esperanto ilo ‘tool’, from German -el ‘(agent suffix)’ {cf Schlüssel ‘key’ ~ schließen ‘lock, shut’)",verb,use,to use,,
iman,🧑‍🤝‍🧑,Arabic إِيمَان ʾīmān 'belief',verb,trust,"to believe, to trust",,
inkatan,📌,Malay ingatan 'memory',verb,remember,to remember,,
inpali,🌼,"Zulu ímbali 'flower, blossom'",noun,flower,"flower, blossom",,
insa,⏺️,"Tok Pisin insait ‘inside, center, stomach’, from English inside",noun,inside,"center, content, inside",,
intisa,⌚,Arabic اِنْتِظَار intiẓār 'wait',modifier,waiting,"waiting, patient",,
into,🏝️,"Zulu indawo 'place, zone, area'",noun,place,"place, space, zone, room, area, region",,
iputu,⏯️,Telugu ఇప్పుడు ippuḍu 'now',modifier,current,"current, in the present",,
isala,💢,Zulu icala 'wrong',modifier,wrong,"incorrect, unfair, wrong, unjust",,
ita,🔽,Arabic إذا ʾiḏā 'if',particle,[context],inverse la (between the main sentence and the context phrase),,
jaki,💩,English yucky,modifier,dirty,"disgusting, obscene, sickly, toxic, unclean, unsanitary",,
jala,📊,"Arabic حالة ḥāl 'state, condition'",noun,condition,"state, condition",,
jan,👤,Cantonese 人 jan4 ‘person’,noun,person,"human being, person, somebody",,
janwa,🦖,Hindi जानवर jānwar 'animal',noun,animal,animal,,
jatila,🙅,"Marathi जटिल jaṭila 'complex, difficult'",modifier,difficult,"complex, difficult",,
jelo,🍋,English yellow,modifier,yellow,"yellow-colored, yellowish",,
jesen,🏞️,"Mandarin 野生 yěshēng 'wild, undomesticated'",noun,wild,"wilderness, nature, forest, jungle",,
jo,👜,Mandarin 有 yǒu ‘have’,verb,have,"to have, to carry, to contain, to hold",,
jun,🪶,Turkish yün 'wool',noun,hair,"hair, wool, fur, feather",,
jupa,🤜,Mandarin 右邊 yòubiān 'right side',noun,right,"the right side, the right direction",,
kaje,🌳,Vietnamese cây 'tree',noun,tree,"tree, wood",,
kake,👏,Teo Chew 結果 gag4 guê2 'result',verb,result,to result in,,
kala,🐟,Finnish kala ‘fish’,noun,fish,"fish, marine animal, sea creature",,
kalama,🔈,"Serbo-Croatian галама galama ‘fuss, noise’",verb,sound,"to produce a sound, to ring, to play (an instrument)",,
kalite,🏷️,"Haitian Creole kalite 'kind', from French qualité",noun,type,"kind, type, class, category, quality",,
kama,🚶,"Tok Pisin kamap ‘event, arrive, happen, become, bring about, summon’, from English come up",verb,become,"to become, to transform into",,
kan,🔗,Finnish kanssa ‘with’,preposition,with,"with, among, in the company of",,
kanja,🍺,"Hindi गांजा gāñjā 'ganja, marihuana, weed'",modifier,intoxicated,"intoxicated, high",,
kanpe,💃,"Punjabi ਕੰਬਣਾ kambṇā 'to tremble', ultimately from Sanskrit कम्प kampa 'trembling, shaking, earthquake'",modifier,shaking,"shaking, wiggling, vibrating (non travelling motion)",,
kanputa,💻,English computer,noun,computer,"computer, technology, mobile phone",,
kanti,🎵,Esperanto kanti 'sing',noun,music,"song, music, poetry",,
kanun,📜,"Arabic قَانُون qānūn 'norm, established principle, canon'; ultimately from Ancient Greek κᾰνών",noun,law,"laws, the Law, standard",,
kapesi,🍪,Greek καφετής kafetís ‘coffee coloured’,modifier,brown,"gray-colored, brown-colored, grayish, brownish",,
kasi,🌱,Finnish kasvi ‘plant’,noun,plant,"plant, vegetation, vegetable",,
kata,📉,Punjabi ਘੱਟ kàtt 'less',modifier,less,less (comparatively),,
keke,🐵,onomatopoeia,noun,primate,"primate: monkey, ape",,
kela,⚽,"Bengali খেলা khela 'game, contest'",verb,play,to play,,
ken,💪,"Tok Pisin ken, ultimately from English can",verb,can,"can, to be able to",,
kenta,,Latin centum 'hundred',numeral,hundred,one hundred,,
ki,↪️,"Māori ki 'to, towards, into'",preposition,to,"to, toward, for, from the perspective of",,
kika,,SI prefix giga,numeral,billion,one billion,,
kikolo,😣,Yoruba kikorò 'bitter',modifier,bitter,bitter,,
kili,🍎,Georgian ხილი xili ‘fruit’,noun,fruit,fruit,,
kilo,,SI prefix kilo,numeral,thousand,one thousand,,
kipisi,✂️,Inuktitut kipisi ‘cut’,verb,cut,"to split, to cut, to sever",,
kisa,📰,"Arabic قِصَّة qiṣṣa 'story, telling'",verb,narrate,to narrate,,
kita,🦏,Telugu గిట్ట giṭṭa 'hoof',noun,ungulate,"ungulate: elephant, deer, giraffe",,
kiwen,💎,"Finnish kiven, genitive of kivi ‘stone’",noun,rock,"hard thing, stone, mineral, rock",,
ko,🍦,"Cantonese 膏 gou1 ‘cream, paste’",noun,paste,"clay, clinging form, dough, semi-solid, paste",,
kokan,🤸,Vietnamese cố gắng 'try',verb,try,"to try, to attempt, to endevour, to pursue",,
komumo,🙌,Zulu ngomumo 'ready',modifier,ready,"ready, prepared",,
kon,💨,"Mandarin 空氣 kōngqì ‘air, atmosphere, ambience, opinion’",noun,air,"air, gas, wind",,
kona,📐,Hindi कोना konā ‘corner’,noun,corner,"corner, knee, elbow, joint, vertex",,
konta,🤓,Xhosa qonda 'understand',verb,understand,to understand,,
kule,🌈,Acadian French couleur ‘color’,noun,color,"color, paint",,
kulupu,👥,"Tongan kulupu, from English group",noun,group,"community, group, company",,
kumi,🎈,"German Gummi, Danish gummi, Swedish gummi",noun,plastic,"plastic, rubber, tire, condom",,
kuton,🤕,Mandarin 苦痛 kǔtòng 'pain',modifier,hurt,"hurt, injured, in pain",,
kuwan,💡,"Mandarin 光 guāng, guǎng",noun,light,light,,
la,🔼,"Acadian French -la, proximal & topical suffix",particle,[context],between the context phrase and the main sentence,,
lajo,📢,Japanese ラジオ rajio 'radio',verb,broadcast,"to broadcast, to announce",,
lakima,😭,Latin lacrima 'tear',modifier,sad,"sad, crying",,
lamo,🦒,Nepali लामो lāmō 'long',modifier,long,"long, tall, extended, prolonged",,
lanpan,📥,"Greek λαμβάνω lamváno ‘take, seize, grasp, receive’",verb,receive,"to take, to receive",,
lape,😴,Dutch slapen ‘sleep’,modifier,sleeping,"sleeping, resting",,
laso,🫐,"Welsh glas ‘blue, inexperienced’",modifier,blue,"blue-colored, blueish",,
lawa,😶,Serbo-Croatian glava глава ‘head’,irregular,head,"(v) to head, to lead, to rule (n) head, mind, plan, rule (m) leading ",,
lekin,🤔,"Hindi लेकिन lekin, ultimately from Arabic لٰكِنْ lākin 'but, however'",particle,but,"but, however",,
leko,🧱,"Lego®, from Danish leg godt ‘play well’",noun,block,"square, block, cube, stairs",,
len,👕,Acadian French linge ‘clothing’,verb,cloth,"to wear, to be covered with",,
lentu,🧻,Basque leundu 'smooth',modifier,smooth,"smooth, fluent, flowing",,
lete,❄️,Acadian French frette ‘cold’,modifier,cold,"cold, cool, uncooked, raw",,
li,▶️,A priori word,particle,[predicate],marks the verb,,
lika,📝,Urdu لکھنا‎ likhnā ‘to write’,verb,write,"to write, to compose",,
lili,🐌,"Tok Pisin liklik ‘small, little’, from Ramoaaina liklik",modifier,small,"little, small",,
lima,5️⃣,Austronesian lima,numeral,five,five,,
linja,〰️,"Finnish linja ‘line’, from Old Swedish linia",noun,line,"long and flexible thing, cord, rope, line, wire",,
lipu,📄,"Finnish lippu ‘flag, banner, ticket’",noun,paper,"flat object, book, document, card, paper, ticket, record, website",,
liso,🤣,"Portuguese riso, ‘laugh’",modifier,laughing,laughing,,
loje,🍓,"Dutch rooie, colloquial inflected form of rood ‘red’",modifier,red,"red-colored, reddish",,
lon,✅,"Tok Pisin long ‘at, in, on, (spacial particle)’, from English along",modifier,real,"real, true, existing",,
luka,✋,"Serbo-Croatian ruka рука ‘hand, arm’",irregular,hand,"(v) to grab (n) arm, hand, tactile organ, wing (m) of the hand, of the arm ",,
lukin,👀,"Tok Pisin lukim ‘see, look at’, luk ‘look’ (from English look) + -im ‘(transitive suffix)' (from English him, ’em)",verb,see,"to look at, to see, to examine, to observe, to read, to watch",,
lupa,🕳️,"Lojban clupa ‘loop’ (from Mandarin 圈 quān, English loop, Hindi पाश pāś, Arabic أنشوطة‏ ʾanšūṭa)",noun,hole,"door, hole, orifice, window, cave",,
ma,🌍,"Finnish maa ‘earth, land’",noun,earth,"earth, land, outdoors, world, country, territory, soil, ground",,
mama,👪,Georgian მამა mama ‘father’,noun,parent,"parent, ancestor, creator, originator, caretaker, sustainer",,
mani,💰,English money,noun,money,"money, cash, savings, wealth",,
masala,😋,"Hindi मसाला masālā 'spice', ultimately from Arabic صَلَحَ‎ ṣalaḥa 'stable'",modifier,spicy,"spicy, tasty, flavored",,
matija,🥈,"Sanskrit मध्य madhya ‘middle, central’",modifier,middle,"middle, medium, mediocre, neither fully one nor the other, between two extremes",,
mawon,🍃,"Vietnamese mỏng 'thin, slender, slim'",modifier,thin,"light, thin",,
meja,🐱,onomatopoeia,noun,cat,"cat, an animal of the Feliformia suborder",,
meka,,SI prefix mega,numeral,million,one million,,
meli,♀️,"Tok Pisin meri ‘woman, wife, feminine’, from Tolai mari ‘pretty’ & English Mary",modifier,female,"female, feminine",,
mi,👈,"Esperanto mi ‘I, me’, from Romance m- ‘(1st person singular oblique)’",noun,me,"I, me",,
mije,♂️,"Finnish mies ‘man, husband’",modifier,male,"male, masculine",,
minsu,⚡,Kannada ಮಿಂಚು mincu ‘lightning’,modifier,electric,electric,,
misa,🐹,Ukrainian миша myša 'mouse',noun,rodent,rodent,,
misali,🎏,"Hindi मिसाल misāl 'example, sample', ultimately from Arabic مِثَال miṯāl",noun,example,"example, sample, version, edition",,
moku,🍽️,Japanese モグモグ mogumogu ‘munching’,verb,eat,"to eat, to drink, to consume, to swallow, to ingest",,
moli,💀,Acadian French mourir ‘die’,modifier,dead,dead,,
monsi,⬅️,Acadian French mon tchu ‘{vulgar} my ass’,noun,back,"back, behind, rear",,
monsuta,😨,"Japanese モンスター monsutā ‘monster’, from English monster",modifier,fear,"scared, fearful",,
moto,🔥,Shona moto 'fire',noun,fire,"fire, flame, plasma",,
mu,🐮,onomatopoeia,noun,cow,"cow, goat, sheep, any animal of the Bovidae family",,
mulu,🌕,"Tamil முழு muḻu 'whole, entire, complete'",modifier,full,"complete, whole, full",,
mun,🌙,English moon,noun,moon,"moon, satellite",,
munkin,🎲,Arabic مُمْكِن mumkin 'possible',modifier,possible,possible,,
musi,🎨,"Esperanto amuzi ‘have fun’, from French amuser",noun,art,"art, recreation",,
mute,👐,"Esperanto multe ‘a lot’, from Latin multus",modifier,many,"many, a lot, much, several, very",,
na,👆,Mandarin 那 nà 'that',irregular,that,(n) that (m) that ,,
naka,🏙️,"Hindi नगर nagar 'city, town'",noun,town,"city, town, village, municipality, human settlement, society",,
nalama,🧸,Hindi नरम narm 'soft',modifier,soft,"soft, flexible, malleable, tender, gentle, ripe",,
nanpa,#️⃣,"Tok Pisin namba ‘number, (ordinal marker)’, from English number",noun,number,number,,
nasa,🌀,Unknown origin,modifier,strange,"unusual, strange, foolish, crazy, silly, stupid, weird",,
nasin,🛣️,"Serbo-Croatian način начин ‘way, method’",noun,way,"way, path, road",,
nata,🖇️,Hindi नाता nātā 'relation',noun,relation,"relation, relationship, connection",,
neje,🐴,onomatopoeia,noun,horse,"horse, donkey, zebra, any animal of the Equidae family",,
nen,⤵️,"Zulu ngenxa 'because of, on behalf of'",preposition,because of,"because of, since",,
nena,👃,Finnish nenä ‘nose’,verb,smell,to smell,,
nesi,🌌,"Igbo n'èzí 'outside, outdoors'",noun,outside,"outside, (outer) space",,
newen,9️⃣,PIE *h₁néwn̥ 'nine',numeral,nine,nine,,
ni,👇,Cantonese 呢 ni1 ‘this’,irregular,this,(n) this (m) this ,,
nimi,💬,Finnish nimi ‘name’,noun,name,"name, word",,
no,❌,English no,modifier,no,"no, not, none",,
noka,🦵,"Serbo-Croatian noga нога ‘foot, leg’",noun,foot,"foot, leg, organ of locomotion",,
nun,🧂,Bengali: নুন nūn 'salt',modifier,salty,salty,,
o,👋,Georgian -ო -o ‘(vocative suffix)’ & English oh,particle,[command],"vocative, imperative, or optative",,
oke,👌,English okay,verb,accept,to accept,,
oliwa,🛢️,Spanish oliva 'olive',noun,oil,"oil, fat, fuel, grease, olive",,
on,☝️,Serbo-Croatian ona она ‘she’,noun,they,"he, she, it, him, her, they",,
one,🤒,"Thai อ่อนแอ on-ae 'weak, feeble'",modifier,weak,"weak, feeble",,
open,🔓,English open,modifier,starting,"starting, beginning",,
osa,🧩,"Finnish osa 'part, piece, component'",noun,piece,"part, piece, particle, element, component, subdivision, segment",,
oto,8️⃣,PIE *h₁oḱtṓw 'eight',numeral,eight,eight,,
pakala,💥,"Tok Pisin bagarap ‘accident’, from English bugger up",modifier,broken,"botched, broken, damaged, harmed, messed up, ruined, spoiled",,
pake,🚧,French barrer 'to lock',modifier,stopped,"stopped, interrupted",,
pali,✊,"Esperanto fari ‘do, make’, from Italian fare & French faire",verb,do,"to do, to take action on, to work on, to build, to make, to prepare, to create, to act, to function",,
palisa,📏,"Serbo-Croatian palica палица ‘bat, rod, cane’",noun,stick,"long hard thing, branch, rod, stick",,
pan,🍞,"Romance pan ‘bread’ & Japanese パン pan, from Portuguese pão",noun,grain,"cereal, grain, bread, pasta",,
pana,📤,"Finnish panna ‘put, set, place’ or Swahili pana ‘give to each other’",verb,give,"to give, to send, to provide, to release",,
papon,🤮,Cantonese 排放 paai4 fong3 'emit',verb,emit,"to emit, to excrete, to exhale, to vomit, to ejaculate",,
pasan,😀,"Hindi पसंद pasand 'liked, favored, preferred', ultimately from Classical Persian پسند 'preference'",modifier,happy,"happy, joyful",,
pati,🥳,English party,verb,celebrate,"to celebrate, to party",,
patila,🙆,French facile ‘easy’,modifier,easy,"easy, simple",,
pawita,🍚,Sanskrit पवित्र pavitra 'pure',modifier,pure,"pure, homogenous",,
pawo,🐶,onomatopoeia,noun,dog,"dog, wolf, bear, any animal of the Caniformia suborder",,
peko,🙏,Italian prego (courtesy formula),particle,please,"please, pardon, [offer help], you're welcome",,
pelu,🔧,Yoruba kpelu,preposition,using,"with the help of, with use of",,
peman,🤝,Persian پیمان peymân 'agreement',noun,deal,"agreement, deal, pact, treaty",,
penke,📆,Mandarin 片刻 piànkè 'moment',noun,moment,"event, instant, moment, instance",,
pesoni,🩹,"Esperanto bezoni 'need, require', from French besoin 'need'",verb,need,to need,,
peta,🥦,"Esperanto verda ‘green’, from Italian 'verde' & French 'vert'",modifier,green,"green-colored, greenish",,
pi,⏹️,"Tok Pisin bilong ‘of’, from English belong",particle,of,"of, relating to, genitive case",,
pilate,⚠️,"Akan pirade 'danger, danagerous'",modifier,dangerous,dangerous,,
pilin,❤️,"Tok Pisin pilim ‘feel’, from pil (from English feel) + -im ‘(transitive suffix)’ (from English him, ’em)",verb,feel,"to feel, to sense",,
pimeja,🎱,Finnish pimeä ‘dark’,modifier,black,"black-colored, blackish, dark, unlit",,
pin,❕,Mandarin 并 bìng ‘in addition; besides; as well; further; too’,modifier,too,"too, also, as well, indeed, even",,
pini,🏁,"French fini ‘finished, completed’ & Tok Pisin pinis ‘(perfective aspect)’, ultimately from English finish",modifier,end,"ending, terminal",,
pipi,🐞,Acadian French bibitte ‘bug’,noun,bug,"bug, insect, ant, spider",,
pisile,⏮️,Hindi पिछले pichle 'previous',modifier,previous,"previous, in the past",,
po,4️⃣,English four,numeral,four,four,,
poka,↔️,"Serbo-Croatian boka бока, genitive of bok бок ‘side, flank’",noun,near,"side, vicinity, nearby area",,
pona,👍,Esperanto bona ‘good’,modifier,good,good,,
popoto,🗻,Bengali পর্বত porbot 'mountain',noun,mountain,"mountain, bump, obtrusion",,
posi,🌚,"Turkish boş 'empty, unoccupied'",modifier,empty,"empty, unstarted",,
powe,🧞,French faux ‘false’,modifier,trick,"pretend, false, unreal",,
pulono,👵,Bengali পুরোনো purono 'old',modifier,old,"old, ancient",,
pume,☁️,French fumer 'smoke',noun,smoke,"smoke, cloud",,
puson,🙋,"Mandarin 服從 fúcóng 'obey, submit'",modifier,obedient,"following, obedient, attentive",,
putala,🧒,"Sanskrit पुत्र putra 'son, child'",noun,offspring,"son, daughter, offspring",,
sa,🐚,Arabic شَيْء‎ šayʾ 'thing',noun,thing,"thing, phenomenon, object, matter, something",,
sajo,🔄,Mandarin 著 zháo 'continuous marker',modifier,ongoing,"ongoing, in continuation",,
saku,🗳️,"Swahili -chagua 'to choose, to elect'",verb,choose,"to chose, to decide",,
sala,⚛️,"Arabic ذَرَّة ḏarra 'tiny particle, atom'",noun,atom,"speck, atom, smallest unit of",,
sama,⚖️,"Finnish sama ‘same’ (from PG *samaz ‘same, alike’) & Esperanto sama ‘same’ (from English same)",modifier,same,"same, similar, equal, fellow",,
san,3️⃣,Mandarin 三 sān 'three',numeral,three,three,,
sankan,‼️,"Thai สำคัญ sam-khan 'noteworthy, special, important, significant'",verb,signify,"to signify, to mean",,
santi,😌,Hindi शांति śānti 'peace',modifier,calm,"peaceful, calm, relaxed, stable",,
sapi,🧼,"Arabic صَافٍ‎ ṣāfin 'pure, clean'",modifier,clean,"clean, sanitized",,
sata,📈,"Hindi ज़्यादा zyādā 'more', ultimately from Arabic زِيَادَة ziyāda 'increase'",modifier,more,more (comparative),,
satalan,🔵,Hindi साधारण sādhāraṇa 'normal',modifier,normal,"normal, common",,
sawapu,📩,Swahili jawabu 'answer' ultimately from Arabic جَوَاب‎ jawāb 'answer',verb,answer,"to answer, to respond",,
seli,♨️,Georgian ცხელი cxeli ‘hot’,modifier,hot,"hot, warm, cooked",,
seme,❓,"Mandarin 什麼 shénme ‘what, something’",particle,what,what? which?,,
senti,*️⃣,SI prefix centi,numeral,percent,percent,,
sepen,7️⃣,PIE *septḿ̥ 'seven',numeral,seven,seven,,
sesi,6️⃣,PIE *swéḱs 'six',numeral,six,six,,
sewi,🛐,Georgian ზევით zevit ‘upwards’,noun,religion,"religion, spirituality",,
si,👉,Finnish sinä ‘you’,noun,you,"you, second person pronoun",,
sike,⭕,English circle,noun,circle,"ball, circle, cycle, sphere, round or circular thing",,
sin,🐣,"Mandarin 新 xīn ‘new, fresh’",modifier,new,"new, fresh, young",,
sinpin,➡️,Cantonese 前邊 tsin4 bin1 ‘in front’,noun,forward,"face, front",,
sipaja,🥉,"Mandarin 失敗 shībài 'to fail, to be defeated'",modifier,lost,"lost, failed, defeated",,
sitelen,🖼️,Dutch schilderen ‘paint’,verb,picture,to draw,,
siten,🪑,Dutch zitten 'to sit',verb,sit,to sit (on),,
soko,🍄,Georgian სოკო sok’o ‘mushroom”,noun,fungus,"fungus, fungi",,
solu,🧐,Turkish soru 'question',verb,ask,"to ask, to question, to inquire",,
sona,🧠,Georgian ცოდნა codna ‘knowledge’,verb,know,"to know, to be skilled in, to be wise about, to have information on",,
soto,🤛,Swahili shoto ‘left side’,noun,left,"the left side, the left direction",,
soweli,🐷,"Georgian ცხოველი cxoveli ‘beastly animal, lively, passionate’",noun,mammal,mammal,,
su,📶,Mandarin 如 rú ‘to be like; as; as if; as though’,preposition,as,"as, like, than",,
sulaki,☮️,"Hindi सुरक्षित surakṣit 'protected, safe'",modifier,safe,"safe, protected",,
suli,🐘,"Finnish suuri ‘big, large, great’",modifier,big,"big, large",,
suno,☀️,Esperanto suno ‘sun’,noun,sun,sun,,
supa,🛏️,"Esperanto surfaco ‘surface’, ultimately from French & English surface",noun,table,"horizontal surface, thing to put or rest something on, floor",,
suti,🔍,Mandarin 具體 jùtǐ 'specific',modifier,specific,"specific, exact, detailed, particular, precise",,
suwi,🍭,"Tok Pisin suwi, ultimately from English sweet",modifier,sweet,sweet,,
ta,🪞,"Classical Syriac ܥܛܦ‎ ʿṭaf ‘to reflect, to return’",modifier,mirrored,"reflected, mirrored, opposite",,
tajan,😡,"Mandarin 討厭 tǎoyàn 'to dislike, to loathe, to hate, to despise'",modifier,angry,"angry, feeling hatred",,
taka,🌊,Turkish dalga 'wave',noun,wave,"rhythm, beat, wave, repeated action",,
talika,📋,"Bengali তালিকা talika 'list, chart, table'",noun,list,"list, series, table, chart, data",,
talili,🧮,"Tagalog daliri 'finger, toe, mentioning things one by one'",irregular,finger,"(v) to count (n) finger, toe (m) of the finger ",,
tan,↩️,Cantonese 從 tsung4 ‘from’,preposition,from,"by, from",,
tana,💭,"Swahili dhana 'concept', ultimately from Arabic ظن ẓann",verb,think,to think,,
tanta,🦷,Hindi दाँत dā̃t 'tooth',irregular,tooth,"(v) to bite (n) tooth, teeth (m) of the teeth ",,
tapa,📦,Hindi डब्बा ḍabbā 'box',noun,box,"container, bag, bowl, box, cup, cupboard, drawer, vessel",,
taso,🏜️,"Tok Pisin tasol ‘just, only, but, however’, ultimately from English that’s all",modifier,only,"only, sole",,
tawa,🚆,English towards,modifier,moving,"moving, mobile, travelling, in motion",,
tawonje,🫂,Zulu ndawonye 'together',modifier,together,"together, united, in solidarity",,
te,⏸️,"Mandarin chinese 的 de, relative clause marker",particle,[relative cl],relative clause marker,,
telo,💧,Acadian French de l’eau ‘(some) water’,noun,water,"water, liquid, juice, sauce, fluid, wet substance, beverages",,
ten,,English ten,numeral,ten,ten,,
tenpo,⏰,"Esperanto tempo ‘time’, ultimately from Latin tempus",noun,time,"time, duration, moment, occasion, period, situation",,
tepaka,🔩,Amharic ጠባቃ t’ebak’a 'firm',modifier,tight,"firm, tight, pressed",,
tewe,🧲,"Hebrew דֶבֶק devek ‘glue, adhesive’",modifier,connected,"joint, stuck, glued, connected",,
tijan,🧘,Hindi ध्यान dhyān 'attention',modifier,attentive,"focused, attentive",,
tijelo,🧍,Serbo-Croatian тијело tijelo ‘body’,noun,body,"body (of person or animal), torso, physical state",,
tile,🐢,Hindi धीरे dhīre 'slowly',modifier,slow,"slow, slowly",,
tini,🦙,Zhuang dinj 'short',modifier,short,short,,
tinto,👂,"Mandarin 聽到 tīngdào 'listen, hear, obey'",verb,hear,"to hear, to listen",,
tisi,🎛️,Mandarin 體系 tǐxì 'system',noun,system,"system, process, method, organization",,
titi,🤱,Swahili titi 'teat',noun,breast,"chest, breast, teat, nipple",,
tiwa,🧗,Punjabi ਦੀਵਾਰ dīvār 'wall' ultimately from Persian دیوار‎ divâr 'wall',noun,wall,"vertical surface, support, wall",,
tiwata,🍸,Samoan tioata 'glass',noun,glass,"glass, cup, china",,
toki,🗣️,"Tok Pisin tok, from English talk",verb,talk,"to communicate, to say, to speak, to talk, to chat",,
tolu,🧪,Estonian toru 'pipe',noun,tube,"pipe, tube",,
tomo,🏠,"Esperanto domo ‘house’, ultimately from Polish dom, Latin domus, Ancient Greek δόμος",noun,house,"building, home, house",,
tonsi,⚧️,Mandarin 同志 tóngzhì ‘comrade (same will/purpose); LGBT+’,modifier,non binary,"trans, gender-non-conforming, non-binary",,
tote,🤏,"Marathi थोडे thoḍe ‘a little, small amount of’",modifier,few,"few, a bit",,
tu,2️⃣,English two & Esperanto du,numeral,two,two,,
tula,🚀,"Marathi दूर dūra 'far, distant'",modifier,far,"far, distant",,
tuntan,💯,Vietnamese đúng đắn 'correct',modifier,correct,"correct, fair, right, just",,
tutu,💓,onomatopoeia,modifier,excitement,"excited, anticipating, aroused, high heartbeat emotion",,
ukumu,🛎️,"Arabic حُكْم‎ ḥukm 'order, command'",verb,command,"to order, to mandate, to command",,
ulokan,🪙,Tamil உலோகம் ulōkam 'metal',modifier,metallic,"hard, metallic",,
umami,🍖,Japanese うま味 umami 'umami',modifier,meat,"meaty, of muscle, umami (flavor), savory",,
unja,🥗,Mandarin 混合 hùnhé 'mixed',modifier,mixed,"mixed, impure, heterogenous",,
unpa,🍆,onomatopoeia,modifier,sex,"erotic, sexual, in a state of intercourse",,
uta,👄,Serbo-Croatian уста usta ‘mouth’,irregular,mouth,"(v) to kiss (n) mouth, lips, oral cavity, jaw (m) of the mouth ",,
utala,⚔️,"Serbo-Croatian ударати udarati ‘strike, hit, hurt’",modifier,fight,"violent, bellicose",,
wa,🥚,"Hawaiian hua 'egg, seed'",irregular,source,"(v) to cause, to be the reason of (n) origin, cause, source, root, spring (m) causative ",,
walaja,😲,Arabic والله wallāh 'by God',modifier,surprise,"surprised, shocked",,
walala,👯,Swahili walaal 'sibling',noun,sibling,"brother, sister, sibling",,
walo,🧄,Finnish valko- ‘white’,modifier,white,"white-colored, whitish, light-coloured, pale",,
wan,1️⃣,English one,numeral,one,one,,
waso,🦅,French oiseau ‘bird’,noun,bird,"bird, flying creature, winged animal",,
wawa,🏋️,"Finnish vahva ‘strong, powerful, thick’",modifier,strong,"strong, powerful, energetic, intense",,
wawasa,😝,Chichewa (wo)wawasa 'sour',modifier,sour,"sour, acidic",,
weka,🛫,"Dutch weg ‘away, gone’",modifier,away,"absent, away, ignored, missing, removed",,
wetu,⭐,Māori whetū ‘star’,noun,star,"star, celestial body",,
wi,⬆️,Korean 위 wi 'above',noun,up,"area above, highest part, top, something elevated",,
wiki,🐇,Hawaiian wikiwiki 'fast',modifier,fast,"fast, quick, quickly",,
wile,🤤,"Dutch willen ‘want, desire'",verb,want,"to want, to wish, to desire",,
wisaja,🏆,"Sanskrit विजय vijaya 'victory, success'",modifier,victorious,victorious,,
woka,⏳,Malagasy vovoka 'dust',noun,powder,"powder, dust, sand",,
wolin,💕,Serbo-Croatian volim волим ‘I love’,verb,love,to love,,`;
